# Generated by Django 4.1.3 on 2022-12-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInstagramAccount',
            fields=[
                ('username', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=151)),
                ('fullName', models.CharField(max_length=65)),
                ('isVerified', models.BooleanField()),
                ('profilePictureURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('expandiId', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('cookies', models.JSONField()),
                ('proxy', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=151)),
                ('followerCount', models.IntegerField()),
                ('followingCount', models.IntegerField(default=-1)),
                ('postsCount', models.IntegerField(default=-1)),
                ('profilePictureURL', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction_HashtagScraped',
            fields=[
                ('reachedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='IgBotApp.externalinstagramaccount')),
                ('reachedAt', models.DateTimeField(auto_now_add=True)),
                ('reachedWhileLoggedInAs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IgBotApp.instagramaccount')),
            ],
            options={
                'ordering': ['reachedAt'],
            },
        ),
    ]
