# Generated by Django 4.1.3 on 2022-12-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('expandiId', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('cookies', models.JSONField()),
                ('proxy', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=151)),
                ('followerCount', models.IntegerField()),
                ('followingCount', models.IntegerField(default=-1)),
                ('postsCount', models.IntegerField(default=-1)),
                ('profilePictureURL', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('username', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('lastTimeUpdated', models.DateTimeField(auto_now=True)),
                ('profileEverFetched', models.BooleanField(default=False)),
                ('isFollower', models.BooleanField(default=False)),
                ('isFollowed', models.BooleanField(default=False)),
                ('isPrivate', models.BooleanField(default=True)),
                ('isMessageable', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('bio', models.CharField(default='Bio not yet retrieved.', max_length=151)),
                ('fullName', models.CharField(default='Name error!', max_length=65)),
                ('profilePictureURL', models.CharField(default='https://scontent-ams2-1.cdninstagram.com/v/t51.2885-19/281440578_1088265838702675_6233856337905829714_n.jpg?stp=dst-jpg_s150x150&_nc_ht=scontent-ams2-1.cdninstagram.com&_nc_cat=1&_nc_ohc=WJLTPTMUm_AAX-gAuPW&edm=ABmJApABAAAA&ccb=7-5&oh=00_AfA1yOvK3rdFZQr7c5GvnRQpva1PKaKXW9FxC9LAI4VwqQ&oe=639E3F98&_nc_sid=6136e7', max_length=10000)),
                ('foundBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IgBotApp.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reachedAt', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField(max_length=250)),
                ('reachedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IgBotApp.lead')),
                ('reachedWhileLoggedInAs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IgBotApp.instagramaccount')),
            ],
        ),
    ]
